### ISSUE TITLE
I got an error when run the step-5‘s app on iphone 

### ISSUE THREAD

**Issue by snaigle** [flutter/friendlychat-steps#53]
`The default Firebase app has not yet been configured.`

here is the full log： 

```
Launching lib/main.dart on iPhone 7 in debug mode...
Running pod install...
Running Xcode build...
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
[Firebase/Messaging][I-IID001001] FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.3900000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
Syncing files to device iPhone 7...
[Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
[Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
)
```

**Comment by LarkAscending** [comment]
Assuming this happens when you run the full_steps/step_5_data_syncing example. 

@snaigle In general this error indicates something is wrong with the Firebase config. Could you please check your Firebase setup to make sure you have a Firebase project and have added Firebase to your iOS app. Once the bundle ID is added, you need to download the GoogleService-Info.plist and copy it to the ios/Runner/Runner directory of your app in Xcode. https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4

You probably have done this, but please check. Also, `flutter doctor` output would be helpful if we need to diagnose further.

/cc @collinjackson

**Comment by LarkAscending** [comment]
OK, I think root cause is you actually need Google Sign-In to do the Database Step. It's not obvious and especially the error message is not helpful. But am guessing that you just went straight to [this step](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#8) without doing the preceding steps. And [Signing users into your app](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#5) is required.

When doing that step, only replace the reverse URL in the Info.plist (2 occurrences). No need to edit the bundle ID, as it's set with a variable now. After that, when you send a message you should get the login screen in Friendlychat. Note that you'll still see the `[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.` error message - that's OK.

Let us know how this goes!

**Comment by snaigle** [comment]
thanks
