### ISSUE TITLE
A problem occurred evaluating project ':app'. showing this message repeatedly... What should I do? note my Flutter and Android ADKs are up to date

### ISSUE THREAD

**Issue by iftee939** [flutter/friendlychat-steps#76]

**Comment by sfshaza2** [comment]
I believe this is because this (very old, pre 1.0) code repo contained the entire project for each step and the old projects just weren't compatible with the current SDK. The code in this repo has been updated. To use it, just create a new Flutter app and then drop the .dart files into it. That should solve your problem. I will soon be releasing an updated version of the codelab itself.
