### ISSUE TITLE
flutter packages get returns error

### ISSUE THREAD

**Issue by madhankumardroid** [flutter/friendlychat-steps#77]
Running "flutter packages get" in step_1_set_up_firebase...     
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because friendlychat depends on firebase_analytics >=0.0.2 <0.3.0 which requires SDK version >=1.8.0 <2.0.0, version solving failed.

pub get failed (1)

I am using Dart 2.1 and the flutter sdk stable version. While running the Packages get in the pubspec.yaml in the step_1_set_up_firebase module, I got this error. How to fix it?

**Comment by sfshaza2** [comment]
Hi, @madhankumardroid. I believe that's because the project was so ancient that the project files were not compatible. I have been updating this codelab *and* the code. We no longer store all the project files (which was a bad idea to begin with), but only the Dart or pubspec.yaml files that have changed. So you would create a new Flutter project and drop your code in. This should alleviate those errors. I will be releasing an updated version of this lab soon, but the code in this repo has already been updated.
